mod 'puppet/nginx', '2.1.1'
mod 'puppetlabs/concat'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/translate'
mod 'puppetlabs/powershell'
mod 'puppetlabs/reboot'
mod 'samuelson/dockeragent'
mod 'puppetlabs/docker'
